version: "3.7"
services:
  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini


  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d


volumes:
    dbdata:
    test_dbdata:
    miniodata: